module.exports = [{liveAttendance: [ { id: 'TlwxosdKTNWX2YutGR_uXg',
    user_id: '16778240',
    user_name: 'Magee Mooney Caliguire',
    device: 'Mac',
    ip_address: '98.234.134.220',
    location: 'Vacaville (US)',
    network_type: 'Wired',
    join_time: '2018-05-17T01:07:05Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20446.0209',
    firstName: 'Magee',
    lastName: 'Mooney',
    moreName: [ 'Caliguire' ],
    room: 'RPT05 Classroom (Wed/Sat)' },
  { id: 'DakaTY0LQbCKF13G_hk_kA',
    user_id: '16779264',
    user_name: 'Amogh Kambale',
    device: 'Mac',
    ip_address: '136.24.142.63',
    location: 'San Francisco (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:07:09Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20446.0209',
    firstName: 'Amogh',
    lastName: 'Kambale',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { user_id: '16780288',
    user_name: 'Vasyl Nesterenko',
    device: 'Mac',
    ip_address: '73.202.138.108',
    location: 'San Francisco (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:07:15Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20199.0205',
    firstName: 'Vasyl',
    lastName: 'Nesterenko',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { user_id: '16781312',
    user_name: 'Eric',
    device: 'Mac',
    ip_address: '74.71.109.183',
    location: 'New York (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:07:16Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.0.38982.0714',
    firstName: 'Eric',
    lastName: undefined,
    room: 'RPT05 Classroom (Wed/Sat)' },
  { id: '0BBAIiPsSsyytYP-CmQnnA',
    user_id: '16782336',
    user_name: 'Daren Lunsford',
    device: 'Mac',
    ip_address: '73.155.50.143',
    location: 'Houston (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:07:23Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.0.38982.0714',
    firstName: 'Daren',
    lastName: 'Lunsford',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { id: 'oaTeMUp7TmmZWgO4DDiDNg',
    user_id: '16783360',
    user_name: 'Kuyik Akpan',
    device: 'Mac',
    ip_address: '107.216.240.179',
    location: 'Union City (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:07:24Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.11049.1024',
    firstName: 'Kuyik',
    lastName: 'Akpan',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { user_id: '16784384',
    user_name: 'michaelflis',
    device: 'Mac',
    ip_address: '73.223.208.182',
    location: 'San Mateo (US)',
    network_type: 'Wired',
    join_time: '2018-05-17T01:07:49Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.11049.1024',
    firstName: 'michaelflis',
    lastName: undefined,
    room: 'RPT05 Classroom (Wed/Sat)' },
  { id: 'dT3uWeVbTIyrmFKv8r4rKQ',
    user_id: '16785408',
    user_name: 'Nick Freeman',
    device: 'Mac',
    ip_address: '98.171.176.21',
    location: 'Santa Barbara (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:08:25Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20446.0209',
    firstName: 'Nick',
    lastName: 'Freeman',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { id: 'GVdAKl3TSrS2GPqJp_KifQ',
    user_id: '16786432',
    user_name: 'Eric Park',
    device: 'Mac',
    ip_address: '136.24.160.2',
    location: 'San Francisco (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:08:26Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20199.0205',
    firstName: 'Eric',
    lastName: 'Park',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { user_id: '16787456',
    user_name: 'Phillip Schmidt',
    device: 'Windows',
    ip_address: '50.39.123.6',
    location: 'Gresham (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:09:43Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.11049.1024',
    firstName: 'Phillip',
    lastName: 'Schmidt',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { id: 'quxFjzjyTqS42oiQw_0aOg',
    user_id: '16778240',
    user_name: 'Al Zadeh',
    device: 'Android',
    ip_address: '172.58.37.144',
    location: 'Oakland (US)',
    network_type: '3G',
    join_time: '2018-05-17T01:08:43Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.24398.0507',
    firstName: 'Al',
    lastName: 'Zadeh',
    room: 'All RPT Zoom Classroom' },
  { id: 'O-ll9h6QRoWZF9v8KhKjdA',
    user_id: '16779264',
    user_name: 'jkumra',
    device: 'Mac',
    ip_address: '136.52.0.67',
    location: 'Irvine (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:12:17Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20446.0209',
    firstName: 'jkumra',
    lastName: undefined,
    room: 'All RPT Zoom Classroom' },
  { id: 'XQJGTf95Q_eZE8KOmfF6uQ',
    user_id: '16780288',
    user_name: 'Himanshu Gaur',
    device: 'Windows',
    ip_address: '70.123.58.175',
    location: 'Austin (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:13:45Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20185.0205',
    firstName: 'Himanshu',
    lastName: 'Gaur',
    room: 'All RPT Zoom Classroom' } ] } ]
