module.exports = [{liveAttendance: [ { id: 'TlwxosdKTNWX2YutGR_uXg',
    user_id: '16778240',
    user_name: 'Magee Mooney Caliguire',
    device: 'Mac',
    ip_address: '98.234.134.220',
    location: 'Vacaville (US)',
    network_type: 'Wired',
    join_time: '2018-05-17T01:07:05Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20446.0209',
    firstName: 'Magee',
    lastName: 'Mooney',
    moreName: [ 'Caliguire' ],
    room: 'RPT05 Classroom (Wed/Sat)' },
  { id: 'DakaTY0LQbCKF13G_hk_kA',
    user_id: '16779264',
    user_name: 'Amogh Kambale',
    device: 'Mac',
    ip_address: '136.24.142.63',
    location: 'San Francisco (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:07:09Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20446.0209',
    firstName: 'Amogh',
    lastName: 'Kambale',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { user_id: '16780288',
    user_name: 'Vasyl Nesterenko',
    device: 'Mac',
    ip_address: '73.202.138.108',
    location: 'San Francisco (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:07:15Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20199.0205',
    firstName: 'Vasyl',
    lastName: 'Nesterenko',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { user_id: '16781312',
    user_name: 'Eric',
    device: 'Mac',
    ip_address: '74.71.109.183',
    location: 'New York (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:07:16Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.0.38982.0714',
    firstName: 'Eric',
    lastName: undefined,
    room: 'RPT05 Classroom (Wed/Sat)' },
  { id: '0BBAIiPsSsyytYP-CmQnnA',
    user_id: '16782336',
    user_name: 'Daren Lunsford',
    device: 'Mac',
    ip_address: '73.155.50.143',
    location: 'Houston (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:07:23Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.0.38982.0714',
    firstName: 'Daren',
    lastName: 'Lunsford',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { id: 'oaTeMUp7TmmZWgO4DDiDNg',
    user_id: '16783360',
    user_name: 'Kuyik Akpan',
    device: 'Mac',
    ip_address: '107.216.240.179',
    location: 'Union City (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:07:24Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.11049.1024',
    firstName: 'Kuyik',
    lastName: 'Akpan',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { user_id: '16784384',
    user_name: 'michaelflis',
    device: 'Mac',
    ip_address: '73.223.208.182',
    location: 'San Mateo (US)',
    network_type: 'Wired',
    join_time: '2018-05-17T01:07:49Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.11049.1024',
    firstName: 'michaelflis',
    lastName: undefined,
    room: 'RPT05 Classroom (Wed/Sat)' },
  { id: 'dT3uWeVbTIyrmFKv8r4rKQ',
    user_id: '16785408',
    user_name: 'Nick Freeman',
    device: 'Mac',
    ip_address: '98.171.176.21',
    location: 'Santa Barbara (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:08:25Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20446.0209',
    firstName: 'Nick',
    lastName: 'Freeman',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { id: 'GVdAKl3TSrS2GPqJp_KifQ',
    user_id: '16786432',
    user_name: 'Eric Park',
    device: 'Mac',
    ip_address: '136.24.160.2',
    location: 'San Francisco (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:08:26Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20199.0205',
    firstName: 'Eric',
    lastName: 'Park',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { user_id: '16787456',
    user_name: 'Phillip Schmidt',
    device: 'Windows',
    ip_address: '50.39.123.6',
    location: 'Gresham (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:09:43Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.11049.1024',
    firstName: 'Phillip',
    lastName: 'Schmidt',
    room: 'RPT05 Classroom (Wed/Sat)' },
  { id: 'quxFjzjyTqS42oiQw_0aOg',
    user_id: '16778240',
    user_name: 'Al Zadeh',
    device: 'Android',
    ip_address: '172.58.37.144',
    location: 'Oakland (US)',
    network_type: '3G',
    join_time: '2018-05-17T01:08:43Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.24398.0507',
    firstName: 'Al',
    lastName: 'Zadeh',
    room: 'All RPT Zoom Classroom' },
  { id: 'O-ll9h6QRoWZF9v8KhKjdA',
    user_id: '16779264',
    user_name: 'jkumra',
    device: 'Mac',
    ip_address: '136.52.0.67',
    location: 'Irvine (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:12:17Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20446.0209',
    firstName: 'jkumra',
    lastName: undefined,
    room: 'All RPT Zoom Classroom' },
  { id: 'XQJGTf95Q_eZE8KOmfF6uQ',
    user_id: '16780288',
    user_name: 'Himanshu Gaur',
    device: 'Windows',
    ip_address: '70.123.58.175',
    location: 'Austin (US)',
    network_type: 'Wifi',
    join_time: '2018-05-17T01:13:45Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20185.0205',
    firstName: 'Himanshu',
    lastName: 'Gaur',
    room: 'All RPT Zoom Classroom' } ,
    { id: '8x0K2tf7Ty6YqtgXkPg7NA',
    user_id: '16778240',
    user_name: 'Samir Habbu',
    device: 'Windows',
    ip_address: '70.119.153.11',
    location: 'Addison (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:43:17Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.18847.0104',
    firstName: 'Samir',
    lastName: 'Habbu',
    room: 'All RPT Zoom Classroom' },
  { id: 'WvZ93-alTjOGMA-I-mLH4w',
    user_id: '16779264',
    user_name: 'Bo Ki Wong',
    device: 'Windows',
    ip_address: '67.244.80.10',
    location: 'New York (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:43:34Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.9355.0929',
    firstName: 'Bo',
    lastName: 'Ki',
    moreName: [ 'Wong' ],
    room: 'All RPT Zoom Classroom' },
  { id: 'eM4LifN-S-a2m4osieRTzg',
    user_id: '16780288',
    user_name: 'Adelle Housker',
    device: 'Mac',
    ip_address: '66.190.26.13',
    location: 'La Crosse (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:43:43Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.9338.0929',
    firstName: 'Adelle',
    lastName: 'Housker',
    room: 'All RPT Zoom Classroom' },
  { id: 'fw_D8-IsR7-tJFHoEvlovg',
    user_id: '16781312',
    user_name: 'michellelockett',
    device: 'Mac',
    ip_address: '69.62.156.24',
    location: 'Carmichael (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:45:42Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.18796.0103',
    firstName: 'michellelockett',
    lastName: undefined,
    room: 'All RPT Zoom Classroom' },
  { id: 'klbzIoKXS-uDBwE5NFLT6g',
    user_id: '16782336',
    user_name: 'Travis Michie',
    device: 'Mac',
    ip_address: '70.121.77.103',
    location: 'Cedar Park (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:45:43Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20199.0205',
    firstName: 'Travis',
    lastName: 'Michie',
    room: 'All RPT Zoom Classroom' },
  { id: '0fvOiIxGSV6sHZQh-lcVEQ',
    user_id: '16783360',
    user_name: 'Happy Situ',
    device: 'Mac',
    ip_address: '173.174.123.111',
    location: 'Austin (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:45:45Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.11049.1024',
    firstName: 'Happy',
    lastName: 'Situ',
    room: 'All RPT Zoom Classroom' },
  { id: 'TlwxosdKTNWX2YutGR_uXg',
    user_id: '16784384',
    user_name: 'Magee Mooney Caliguire',
    device: 'Mac',
    ip_address: '98.234.134.220',
    location: 'Vacaville (US)',
    network_type: 'Wired',
    join_time: '2018-05-18T03:45:46Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20446.0209',
    firstName: 'Magee',
    lastName: 'Mooney',
    moreName: [ 'Caliguire' ],
    room: 'All RPT Zoom Classroom' },
  { id: 'Yla7bM4iRluhMi7wlIC1CQ',
    user_id: '16785408',
    user_name: 'sravanthi karanam',
    device: 'Mac',
    ip_address: '73.162.11.68',
    location: 'Saratoga (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:45:54Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.11049.1024',
    firstName: 'sravanthi',
    lastName: 'karanam',
    room: 'All RPT Zoom Classroom' },
  { user_id: '16786432',
    user_name: 'alexwells',
    device: 'Mac',
    ip_address: '69.75.40.82',
    location: 'San Diego (US)',
    network_type: 'Others',
    join_time: '2018-05-18T03:45:57Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.9338.0929',
    firstName: 'alexwells',
    lastName: undefined,
    room: 'All RPT Zoom Classroom' },
  { id: '2DkzEdlqR6qs5OheK30lRw',
    user_id: '16787456',
    user_name: 'Hubert Nimitanakit',
    device: 'Mac',
    ip_address: '73.231.9.177',
    location: 'Danville (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:46:01Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.11049.1024',
    firstName: 'Hubert',
    lastName: 'Nimitanakit',
    room: 'All RPT Zoom Classroom' },
  { id: 'kt4fTEqgRDK89bIwuO6ZqA',
    user_id: '16788480',
    user_name: 'Joseph',
    device: 'Windows',
    ip_address: '76.174.30.104',
    location: 'Reseda (US)',
    network_type: 'Wired',
    join_time: '2018-05-18T03:46:14Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.24407.0507',
    firstName: 'Joseph',
    lastName: undefined,
    room: 'All RPT Zoom Classroom' },
  { id: 'Cf_tEJ_2QPCa2jQWbnnwfA',
    user_id: '16789504',
    user_name: 'Amena Kauser Syeda',
    device: 'Mac',
    ip_address: '108.20.21.41',
    location: 'Acton (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:46:17Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20199.0205',
    firstName: 'Amena',
    lastName: 'Kauser',
    moreName: [ 'Syeda' ],
    room: 'All RPT Zoom Classroom' },
  { id: 'Agjnke2KSEmqcvOVWqGcsw',
    user_id: '16790528',
    user_name: 'Sarkhan Koshkarli',
    device: 'Mac',
    ip_address: '73.158.64.217',
    location: 'Sunnyvale (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:46:18Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20199.0205',
    firstName: 'Sarkhan',
    lastName: 'Koshkarli',
    room: 'All RPT Zoom Classroom' },
  { id: '71yxT-biQA2pW6MhrELyzA',
    user_id: '16791552',
    user_name: 'Ted Green',
    device: 'Mac',
    ip_address: '73.162.189.28',
    location: 'Santa Clara (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:46:19Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20199.0205',
    firstName: 'Ted',
    lastName: 'Green',
    room: 'All RPT Zoom Classroom' },
  { id: 'iBKiGa4DTsyKT96IDSSvBA',
    user_id: '16792576',
    user_name: 'Jeramiah Cerda',
    device: 'Mac',
    ip_address: '24.192.98.2',
    location: '',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:46:19Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.0.36452.0616',
    firstName: 'Jeramiah',
    lastName: 'Cerda',
    room: 'All RPT Zoom Classroom' },
  { id: '5XcW8lsESnSNbgeIyY4IkQ',
    user_id: '16793600',
    user_name: 'Leslie Pajuelo',
    device: 'Mac',
    ip_address: '99.165.37.105',
    location: 'Carlsbad (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:46:27Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.23501.0416',
    firstName: 'Leslie',
    lastName: 'Pajuelo',
    room: 'All RPT Zoom Classroom' },
  { id: 'X6LGuAqLQISTCE9Z56yXOg',
    user_id: '16794624',
    user_name: 'Debalina Mukherjee',
    device: 'Mac',
    ip_address: '24.130.1.228',
    location: 'San Ramon (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:46:28Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.9338.0929',
    firstName: 'Debalina',
    lastName: 'Mukherjee',
    room: 'All RPT Zoom Classroom' },
  { id: '7EClNsJTR6WKfmB-ZAczBA',
    user_id: '16795648',
    user_name: 'Bella',
    device: 'Mac',
    ip_address: '67.180.189.106',
    location: 'San Jose (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:46:36Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.0.36452.0616',
    firstName: 'Bella',
    lastName: undefined,
    room: 'All RPT Zoom Classroom' },
  { id: 'vO17RbqPRLWP8-w6PRqZtQ',
    user_id: '16796672',
    user_name: 'Zoey',
    device: 'Windows',
    ip_address: '67.174.192.117',
    location: 'Sonoma (US)',
    network_type: 'Wired',
    join_time: '2018-05-18T03:46:37Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.23501.0416',
    firstName: 'Zoey',
    lastName: undefined,
    room: 'All RPT Zoom Classroom' },
  { id: '_gMETyniQMGJu_9Q-ryqgw',
    user_id: '16797696',
    user_name: 'Seth Shill',
    device: 'Mac',
    ip_address: '65.189.55.85',
    location: 'Dayton (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:46:39Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.0.38982.0714',
    firstName: 'Seth',
    lastName: 'Shill',
    room: 'All RPT Zoom Classroom' },
  { id: 'k2oW8pIzRsiaQWtwfdIamg',
    user_id: '16798720',
    user_name: 'Neiman Chen',
    device: 'Mac',
    ip_address: '73.71.156.28',
    location: 'Cupertino (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:47:03Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.0.38982.0714',
    firstName: 'Neiman',
    lastName: 'Chen',
    room: 'All RPT Zoom Classroom' },
  { id: 'NSgg3bF5TE6M83037GbLeg',
    user_id: '16799744',
    user_name: 'Yang Chen',
    device: 'Windows',
    ip_address: '24.23.172.185',
    location: 'Cotati (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:47:06Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.24407.0507',
    firstName: 'Yang',
    lastName: 'Chen',
    room: 'All RPT Zoom Classroom' },
  { id: 'V1I3oCwMS6GB3SApodZB7A',
    user_id: '16800768',
    user_name: 'Jared Horne',
    device: 'Mac',
    ip_address: '70.94.59.24',
    location: 'Liberty (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:47:09Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.0.29208.0410',
    firstName: 'Jared',
    lastName: 'Horne',
    room: 'All RPT Zoom Classroom' },
  { id: 'dT3uWeVbTIyrmFKv8r4rKQ',
    user_id: '16801792',
    user_name: 'Nick Freeman',
    device: 'Mac',
    ip_address: '98.171.176.21',
    location: 'Santa Barbara (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:47:10Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20446.0209',
    firstName: 'Nick',
    lastName: 'Freeman',
    room: 'All RPT Zoom Classroom' },
  { user_id: '16802816',
    user_name: 'Jay Wilson Jr.',
    device: 'Mac',
    ip_address: '24.126.31.76',
    location: 'Germantown (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:47:46Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.0.36452.0616',
    firstName: 'Jay',
    lastName: 'Wilson',
    moreName: [ 'Jr.' ],
    room: 'All RPT Zoom Classroom' },
  { user_id: '16803840',
    user_name: 'Chris Poole',
    device: 'Mac',
    ip_address: '64.187.162.193',
    location: 'Bellevue (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:48:51Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.10062.1016',
    firstName: 'Chris',
    lastName: 'Poole',
    room: 'All RPT Zoom Classroom' },
  { user_id: '16804864',
    user_name: 'Jef Leung',
    device: 'Mac',
    ip_address: '50.242.81.83',
    location: 'Sunnyvale (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:48:56Z',
    leave_time: '2018-05-18T03:50:46Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.0.38982.0714',
    firstName: 'Jef',
    lastName: 'Leung',
    room: 'All RPT Zoom Classroom' },
  { id: 'Lwn-11zMSyCFIflpcOR9_w',
    user_id: '16805888',
    user_name: 'Chris Wohlers',
    device: 'Mac',
    ip_address: '73.189.26.247',
    location: 'Santa Cruz (US)',
    network_type: 'Wifi',
    join_time: '2018-05-18T03:48:56Z',
    share_application: false,
    share_desktop: false,
    share_whiteboard: false,
    recording: false,
    pc_name: '',
    domain: '',
    mac_addr: '',
    harddisk_id: '',
    version: '4.1.20199.0205',
    firstName: 'Chris',
    lastName: 'Wohlers',
    room: 'All RPT Zoom Classroom' } ] } ]
